#ifndef BW_FOUNDATION_VERSION_H
#define BW_FOUNDATION_VERSION_H

#include "Bw/Base/Preprocessor.h"

#define BW_FOUNDATION_VERSION_MAJOR 0
#define BW_FOUNDATION_VERSION_MINOR 0
#define BW_FOUNDATION_VERSION_PATCH 0
#define BW_FOUNDATION_VERSION_STRING BW_GET_VERSION_STRING("FoundationLib-", BW_FOUNDATION_VERSION_MAJOR, BW_FOUNDATION_VERSION_MINOR, BW_FOUNDATION_VERSION_PATCH, "")

#endif	// BW_FOUNDATION_VERSION_H