#ifndef BW_BASE_VERSION_H
#define BW_BASE_VERSION_H

#include "Bw/Base/Preprocessor.h"

#define BW_BASE_VERSION_MAJOR 0
#define BW_BASE_VERSION_MINOR 0
#define BW_BASE_VERSION_PATCH 0
#define BW_BASE_VERSION_STRING BW_GET_VERSION_STRING("BaseLib-", BW_BASE_VERSION_MAJOR, BW_BASE_VERSION_MINOR, BW_BASE_VERSION_PATCH, "")

#endif	// BW_BASE_VERSION_H