#ifndef BW_ENGINE_VERSION_H
#define BW_ENGINE_VERSION_H

#define BW_ENGINE_VERSION_MAJOR 0
#define BW_ENGINE_VERSION_MINOR 0
#define BW_ENGINE_VERSION_PATCH 0
#define BW_ENGINE_VERSION_STRING BW_GET_VERSION_STRING("BitwiseEngine-", BW_ENGINE_VERSION_MAJOR, BW_ENGINE_VERSION_MINOR, BW_ENGINE_VERSION_PATCH, "")

#endif	// BW_ENGINE_VERSION_H