#ifndef BW_COLLECTIONS_EXPORT_H
#define BW_COLLECTIONS_EXPORT_H

#include "Bw/Base/Macros.h"

#if defined(BW_COLLECTIONS_EXPORT)
#	define BW_COLLECTIONS_API BW_API_EXPORT
#else
#	define BW_COLLECTIONS_API BW_API_IMPORT
#endif

#endif	// BW_COLLECTIONS_EXPORT_H